version: '3'

services:
  grade-prediction-app:
    # image: quynhud/grade-prediction-app:latest
    build: .
    container_name: grade-prediction-app
    ports:
      - "8008:8008"
    environment:
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_USER=admin
      - MINIO_PASSWORD=admin1234
    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: minio_s3
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1234
    volumes:
      - ./data:/data