name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    types:
        - closed
    branches: [ "master" ]


jobs:

  docker_and_linter:
    # if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/grade-prediction-app:test

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/grade-prediction-app:test

    # - name: Run application
    #   run: docker-compose up -d

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.9
    - name: Install flake8
      run: pip install flake8
    - name: Run flake8 linter
      run: flake8 src
    
    # - name: Run tests
    #   run: pytest src/test_app.py